source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

# 下記コマンドで Gemfile.lock の RUBY VERSION を更新する。
# `docker compose run --rm app_setup bundle update --ruby`
ruby file: '../../.ruby-version'

gem 'sassc-rails', '>= 2.1.0'

gem 'bootstrap', '4.3.0'

gem 'ransack'

gem 'rmagick'
